server:
  port: 8080

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

logging:
  level:
    org.springframework.boot.actuate: DEBUG
